// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { CustomDatabaseFunctions } from '../../types/supabase-extensions';

const SUPABASE_URL = "https://ieotixprkfglummoobkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllb3RpeHBya2ZnbHVtbW9vYmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMjUxNjUsImV4cCI6MjA2NDkwMTE2NX0.hWAxW1tBbMQr3BOPSPOR57eiYvzWzDjaUMjigLyUaGQ";

// Merge custom functions with the auto-generated database type
type ExtendedDatabase = Database & {
  public: Database['public'] & {
    Functions: Database['public']['Functions'] & CustomDatabaseFunctions;
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);